import os

def register_compile_deps():
  goals = []
  lib_rel_path = 'target/lib/'
  lib_path = get_base_path() + '/' + lib_rel_path
  deps = [f for f in os.listdir(lib_path) if os.path.isfile(os.path.join(lib_path, f)) and f.endswith('.jar')]
  for dep in deps:
    name = dep[:-4]
    prebuilt_jar(
      name = name,
      binary_jar = lib_rel_path + '/' + dep
    )
    goals.append(':' + name)
  return goals

# For simplicity, let Maven handle the dependencies.
# Buck would advocate checking them into the repo.
COMPILE_DEPS = register_compile_deps()

java_library(
  name = 'vertx-hot-example1-lib',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/resources/**/*']),
  resources_root = 'src/main/resources',
  deps = COMPILE_DEPS,
  visibility = ['PUBLIC']
)

java_binary(
  name = 'vertx-hot-example1',
  deps = [':vertx-hot-example1-lib']
)